on:
  push:
    branches:
      - master
jobs:
   Create-Chocolatey-Package:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup
      run: ./helpers.ps1
      shell: pwsh
    
    - name: Pack Package
      run: ./run.ps1
      shell: pwsh
    
    - name: Push to Github Packages
      run: ./publish.ps1
      shell: pwsh
      env:
        TOKEN: ${{secrets.GITHUB_TOKEN}}
      
